main:main.c delect.c update.c init_sqlist.c insert.c get_element.c display.c
	gcc main.c delect.c update.c init_sqlist.c insert.c get_element.c display.c -o main

main_update:main_update.c delect.c update.c init_sqlist.c insert.c get_element.c
	gcc main_update.c delect.c update.c init_sqlist.c insert.c get_element.c -o main_update