main:initialization.c main.c insert.c delect.c update.c get_element.c location.c get_length.c display.c
	gcc initialization.c main.c insert.c delect.c update.c get_element.c location.c get_length.c display.c -o main
